modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="adventure"
version="1.0.0"
displayName="adventure+"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="USER, MCreator"

[[dependencies.adventure]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




